import { CONFIG } from "./config.js";
import { clearCart, getCart, removeCartItem, updateCartItem, cartSubtotal } from "./cart.js";
import { supabase } from "./supabase-client.js";
import { escapeHtml, money } from "./utils.js";
import { initStoreShell } from "./store-shell.js";

initStoreShell(); const itemsRoot=document.querySelector("[data-cart-items]"), subtotalNode=document.querySelector("[data-subtotal]"), form=document.querySelector("[data-checkout-form]"), result=document.querySelector("[data-checkout-result]");
function render(){const cart=getCart(); subtotalNode.textContent=money(cartSubtotal()); form.hidden=!cart.length; itemsRoot.innerHTML=cart.length?cart.map(item=>`<article class="cart-item">${item.imageUrl?`<img src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.name)}">`:'<div class="cart-item__empty-image">AM</div>'}<div><h3>${escapeHtml(item.name)}</h3>${item.variantLabel?`<p>${escapeHtml(item.variantLabel)}</p>`:""}<p>${money(item.unitPrice)} cada</p><label class="field">Quantidade<input data-quantity="${escapeHtml(item.key)}" type="number" min="1" max="${item.stock}" value="${item.quantity}"></label><button class="link-button" data-remove="${escapeHtml(item.key)}">Remover</button></div><strong class="cart-item__price">${money(item.unitPrice*item.quantity)}</strong></article>`).join(""):'<div class="empty-state"><h2>Seu carrinho está vazio</h2><p>Escolha uma peça para continuar.</p><a class="button" href="produtos.html">Ver produtos</a></div>';}
itemsRoot.addEventListener("change",e=>{if(e.target.matches("[data-quantity]")){updateCartItem(e.target.dataset.quantity,Number(e.target.value));render();}}); itemsRoot.addEventListener("click",e=>{const button=e.target.closest("[data-remove]");if(button){removeCartItem(button.dataset.remove);render();}});
form.addEventListener("submit",async event=>{event.preventDefault(); const cart=getCart(); if(!cart.length)return; const button=form.querySelector("button[type=submit]"); button.disabled=true; button.textContent="Validando pedido…"; result.innerHTML=""; const fields=new FormData(form); const customer={name:fields.get("name"),phone:fields.get("phone"),email:fields.get("email"),address:fields.get("address")}; const items=cart.map(item=>({product_id:item.productId,variant_id:item.variantId,quantity:item.quantity}));
  const {data,error}=await supabase.rpc("create_guest_order",{p_customer:customer,p_items:items,p_notes:fields.get("notes")||null}); button.disabled=false;button.textContent="Finalizar pelo WhatsApp";
  if(error){result.innerHTML=`<p class="notice">Não foi possível registrar o pedido: ${escapeHtml(error.message)}</p>`;return;}
  const lines=[`Olá, gostaria de fazer este pedido na Amoremio:`,``,`Pedido nº ${data.order_number}`, ...data.items.flatMap(item=>["",`Produto: ${item.product_name}`,item.variant?`Variação: ${item.variant}`:null,`Quantidade: ${item.quantity}`,`Valor: ${money(item.total)}`].filter(Boolean)),"",`Subtotal: ${money(data.subtotal)}`,`Frete: ${money(data.shipping)}`,`Total: ${money(data.total)}`,"",`Cliente: ${customer.name}`,`Telefone: ${customer.phone}`,`E-mail: ${customer.email}`,`Endereço: ${customer.address}`,fields.get("notes")?`Observações: ${fields.get("notes")}`:null].filter(Boolean); const url=`https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(lines.join("\n"))}`; clearCart();render(); result.innerHTML=`<div class="notice"><strong>Pedido nº ${data.order_number} registrado com sucesso.</strong><br>Agora envie a mensagem para a Amoremio.</div><a class="button" href="${url}" target="_blank" rel="noopener">Abrir WhatsApp</a>`; window.open(url,"_blank","noopener");}); render();
