import { supabase } from "../js/supabase-client.js";
import { escapeHtml, money } from "../js/utils.js";
import { ProductGalleryEditor } from "./gallery.js";
import { resolveProductImages } from "../js/products.js?v=20260730-4";
import { initDataBackups } from "./data-backups.js?v=20260730-2";
import { defaultCare, discountPercent, isSaleProduct, publicProductTitle } from "../js/product-commercial.js?v=20260730-1";

const globalMessage=document.querySelector("[data-global-message]");let categories=[],products=[];
const say=(text)=>{globalMessage.textContent=text;setTimeout(()=>{if(globalMessage.textContent===text)globalMessage.textContent=""},5000)};
const slugify=(text)=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const{data:{session}}=await supabase.auth.getSession();if(!session)location.replace("index.html");else{const{data:profile}=await supabase.from("profiles").select("role").eq("id",session.user.id).maybeSingle();if(profile?.role!=="admin"){await supabase.auth.signOut();location.replace("index.html")}}
document.querySelector("[data-products-list]").addEventListener("click",e=>{const edit=e.target.closest("[data-edit-product]");if(!edit)return;const product=products.find(item=>item.id===edit.dataset.editProduct),select=productForm.elements.material;if(product?.material&&![...select.options].some(option=>option.value===product.material))select.add(new Option(product.material,product.material))},{capture:true});

document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("is-active",x===button));document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("is-active",x.dataset.panel===button.dataset.tab));if(button.dataset.tab==="orders")loadOrders();if(button.dataset.tab==="customers")loadCustomers()}));
document.querySelector("[data-logout]").addEventListener("click",async()=>{await supabase.auth.signOut();location.replace("index.html")});

async function loadCategories(){const{data,error}=await supabase.from("categories").select("*").order("name");if(error)return say(error.message);categories=data||[];document.querySelector('[name="category_id"]').innerHTML='<option value="">Sem categoria</option>'+categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("");document.querySelector("[data-categories-list]").innerHTML=categories.map(c=>`<article><div><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.slug)} · ${c.active?"Ativa":"Inativa"}</p></div><div class="admin-actions"><button data-edit-category="${c.id}">Editar</button><button class="secondary" data-toggle-category="${c.id}">${c.active?"Desativar":"Ativar"}</button></div></article>`).join("")||"<p>Nenhuma categoria cadastrada.</p>"}
const categoryForm=document.querySelector("[data-category-form]");categoryForm.elements.name.addEventListener("input",()=>{if(!categoryForm.elements.id.value)categoryForm.elements.slug.value=slugify(categoryForm.elements.name.value)});categoryForm.addEventListener("submit",async e=>{e.preventDefault();const v=new FormData(categoryForm),id=v.get("id"),payload={name:v.get("name").trim(),slug:v.get("slug").trim(),image_url:v.get("image_url")||null,active:v.get("active")==="on"};const query=id?supabase.from("categories").update(payload).eq("id",id):supabase.from("categories").insert(payload);const{error}=await query;if(error)return say(error.message);categoryForm.reset();categoryForm.elements.id.value="";say("Categoria salva.");loadCategories()});
document.querySelector("[data-categories-list]").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit-category]"),toggle=e.target.closest("[data-toggle-category]");if(edit){const c=categories.find(x=>x.id===edit.dataset.editCategory);categoryForm.elements.id.value=c.id;categoryForm.elements.name.value=c.name;categoryForm.elements.slug.value=c.slug;categoryForm.elements.image_url.value=c.image_url||"";categoryForm.elements.active.checked=c.active;categoryForm.scrollIntoView({behavior:"smooth"})}if(toggle){const c=categories.find(x=>x.id===toggle.dataset.toggleCategory);const{error}=await supabase.from("categories").update({active:!c.active}).eq("id",c.id);if(error)say(error.message);else loadCategories()}});

function renderProductsList(){const term=document.querySelector("[data-product-search]").value.trim().toLowerCase(),visible=products.filter(p=>!term||p.name.toLowerCase().includes(term)||p.sku.toLowerCase().includes(term));document.querySelector("[data-products-list]").innerHTML=visible.map(p=>`<article><div><h3>${escapeHtml(publicProductTitle(p))}</h3><p>SKU ${escapeHtml(p.sku)} · ${escapeHtml(p.material||"Material a informar")} · ${money(p.promotional_price??p.price)} · Estoque ${p.stock} · ${p.active?"Ativo":"Inativo"}${isSaleProduct(p)?` · Saldo ${discountPercent(p)}%`:""}${p.featured?" · Destaque":""}</p></div><div class="admin-actions"><button data-edit-product="${p.id}">Editar</button><button class="secondary" data-toggle-product="${p.id}">${p.active?"Desativar":"Ativar"}</button></div></article>`).join("")||"<p>Nenhum produto encontrado.</p>"}
async function loadProducts(){const{data,error}=await supabase.from("products").select("*, categories(name), product_images(*), product_variants(*)").order("created_at",{ascending:false});if(error)return say(error.message);products=data||[];try{await resolveProductImages(products)}catch(error){say(`Algumas imagens não puderam ser carregadas: ${error.message}`)}renderProductsList()}
document.querySelector("[data-product-search]").addEventListener("input",renderProductsList);
const productForm=document.querySelector("[data-product-form]"),variantsRoot=document.querySelector("[data-variants]"),template=document.querySelector("#variant-template");function addVariant(v={}){const row=template.content.firstElementChild.cloneNode(true);row.querySelector('[name="variant_name"]').value=v.name||"";row.querySelector('[name="variant_value"]').value=v.value||"";row.querySelector('[name="variant_adjustment"]').value=v.price_adjustment||0;row.querySelector('[name="variant_stock"]').value=v.stock||0;row.dataset.id=v.id||"";variantsRoot.append(row)}document.querySelector("[data-add-variant]").addEventListener("click",()=>addVariant());variantsRoot.addEventListener("click",e=>e.target.closest("[data-remove-variant]")?.parentElement.remove());
const gallery=new ProductGalleryEditor({supabase,root:document.querySelector("[data-image-preview]"),input:productForm.elements.images,progress:document.querySelector("[data-gallery-progress]"),message:document.querySelector("[data-gallery-message]")});
function commercialPreview(){const candidate={name:productForm.elements.name.value,material:productForm.elements.material.value,auto_material_in_title:productForm.elements.auto_material_in_title.checked,price:Number(productForm.elements.price.value||0),promotional_price:productForm.elements.promotional_price.value?Number(productForm.elements.promotional_price.value):null,stock:Number(productForm.elements.stock.value||0),active:productForm.elements.active.checked},discount=discountPercent(candidate),sale=isSaleProduct(candidate);productForm.querySelector("[data-public-title-preview]").textContent=publicProductTitle(candidate)||"Aguardando o nome do produto";productForm.querySelector("[data-discount-preview]").textContent=`${discount}%`;productForm.querySelector("[data-sale-preview]").textContent=sale?"Este produto aparecerá em Saldos.":"Este produto não aparecerá em Saldos.";productForm.querySelector(".commercial-status").classList.toggle("is-sale",sale)}
function resetProduct(){productForm.reset();productForm.elements.id.value="";variantsRoot.innerHTML="";gallery.reset();productForm.classList.add("hidden");commercialPreview()};document.querySelector("[data-new-product]").addEventListener("click",()=>{resetProduct();productForm.classList.remove("hidden");productForm.elements.name.focus()});document.querySelector("[data-cancel-product]").addEventListener("click",resetProduct);productForm.elements.name.addEventListener("input",()=>{if(!productForm.elements.id.value)productForm.elements.slug.value=slugify(productForm.elements.name.value);commercialPreview()});["price","promotional_price","stock","active","auto_material_in_title"].forEach(name=>productForm.elements[name].addEventListener("input",commercialPreview));productForm.elements.material.addEventListener("change",()=>{if(!productForm.elements.care_instructions.value.trim()||productForm.elements.care_instructions.dataset.suggested==="true"){productForm.elements.care_instructions.value=defaultCare(productForm.elements.material.value);productForm.elements.care_instructions.dataset.suggested="true"}commercialPreview()});productForm.elements.care_instructions.addEventListener("input",()=>{productForm.elements.care_instructions.dataset.suggested="false"});
document.querySelector("[data-products-list]").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit-product]"),toggle=e.target.closest("[data-toggle-product]");if(toggle){const p=products.find(x=>x.id===toggle.dataset.toggleProduct);const{error}=await supabase.from("products").update({active:!p.active}).eq("id",p.id);if(error)say(error.message);else loadProducts()}if(edit){const p=products.find(x=>x.id===edit.dataset.editProduct);resetProduct();productForm.classList.remove("hidden");["id","name","sku","slug","description","material","material_details","care_instructions","dimensions","category_id","price","promotional_price","stock"].forEach(k=>productForm.elements[k].value=p[k]??"");productForm.elements.active.checked=p.active;productForm.elements.featured.checked=p.featured;productForm.elements.auto_material_in_title.checked=p.auto_material_in_title!==false;productForm.elements.care_instructions.dataset.suggested="false";(p.product_variants||[]).forEach(addVariant);gallery.load(p);commercialPreview();productForm.scrollIntoView({behavior:"smooth"})}});
productForm.addEventListener("submit",async e=>{e.preventDefault();const button=productForm.querySelector('button[type="submit"]');button.disabled=true;say("Salvando produto…");const v=new FormData(productForm),id=v.get("id"),sku=v.get("sku").trim().toUpperCase(),payload={name:v.get("name").trim(),sku,slug:v.get("slug").trim(),description:v.get("description")||"",material:v.get("material")||null,material_details:v.get("material_details")||null,care_instructions:v.get("care_instructions").trim()||defaultCare(v.get("material")),auto_material_in_title:v.get("auto_material_in_title")==="on",dimensions:v.get("dimensions")||null,category_id:v.get("category_id")||null,price:Number(v.get("price")),promotional_price:v.get("promotional_price")?Number(v.get("promotional_price")):null,stock:Number(v.get("stock")),active:v.get("active")==="on",featured:v.get("featured")==="on"};let skuQuery=supabase.from("products").select("id").ilike("sku",sku).limit(1);if(id)skuQuery=skuQuery.neq("id",id);const{data:duplicate,error:skuError}=await skuQuery;if(skuError){button.disabled=false;return say(skuError.message)}if(duplicate?.length){button.disabled=false;return say("Este SKU já está sendo usado por outro produto.")}let productId=id;if(id){const{error}=await supabase.from("products").update(payload).eq("id",id);if(error){button.disabled=false;return say(error.message)}}else{const{data,error}=await supabase.from("products").insert(payload).select("id").single();if(error){button.disabled=false;return say(error.message)}productId=data.id}
  const rows=[...variantsRoot.children].map(row=>({product_id:productId,name:row.querySelector('[name="variant_name"]').value.trim(),value:row.querySelector('[name="variant_value"]').value.trim(),price_adjustment:Number(row.querySelector('[name="variant_adjustment"]').value||0),stock:Number(row.querySelector('[name="variant_stock"]').value||0)})).filter(x=>x.name&&x.value);if(id){const{error}=await supabase.from("product_variants").delete().eq("product_id",productId);if(error){button.disabled=false;return say(error.message)}}if(rows.length){const{error}=await supabase.from("product_variants").insert(rows);if(error){button.disabled=false;return say(error.message)}}
  try{await gallery.save(productId,payload.name)}catch(error){button.disabled=false;return say(`Produto salvo, mas a galeria precisa de atenção: ${error.message}`)}
  button.disabled=false;say("Produto salvo e publicado no catálogo.");resetProduct();await loadProducts()});

async function loadOrders(){const root=document.querySelector("[data-orders-list]");root.innerHTML="Carregando…";const{data,error}=await supabase.from("orders").select("*, order_items(*)").order("created_at",{ascending:false});if(error)return root.textContent=error.message;root.innerHTML=(data||[]).map(o=>`<article><div><h3>Pedido nº ${o.order_number} · ${escapeHtml(o.customer_name)}</h3><p>${new Date(o.created_at).toLocaleString("pt-BR")} · ${money(o.total)} · ${escapeHtml(o.phone)}</p><div class="order-items">${o.order_items.map(i=>`${i.quantity}× ${escapeHtml(i.product_name)}${i.product_sku?` · SKU ${escapeHtml(i.product_sku)}`:""}${i.product_material?` · ${escapeHtml(i.product_material)}`:""}${i.variant?` (${escapeHtml(i.variant)})`:""}`).join("<br>")}</div></div><select class="status-select" data-order-status="${o.id}">${["pending","confirmed","preparing","shipped","completed","cancelled"].map(s=>`<option value="${s}" ${s===o.status?"selected":""}>${({pending:"Pendente",confirmed:"Confirmado",preparing:"Preparando",shipped:"Enviado",completed:"Concluído",cancelled:"Cancelado"})[s]}</option>`).join("")}</select></article>`).join("")||"<p>Nenhum pedido recebido.</p>"}document.querySelector("[data-refresh-orders]").addEventListener("click",loadOrders);document.querySelector("[data-orders-list]").addEventListener("change",async e=>{if(e.target.matches("[data-order-status]")){const{error}=await supabase.from("orders").update({status:e.target.value}).eq("id",e.target.dataset.orderStatus);say(error?error.message:"Status do pedido atualizado.")}});
async function loadCustomers(){const root=document.querySelector("[data-customers-list]"),{data,error}=await supabase.from("customers").select("*").order("created_at",{ascending:false});if(error)return root.textContent=error.message;root.innerHTML=(data||[]).map(c=>`<article><div><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.phone)} · ${escapeHtml(c.email)}<br>${escapeHtml(c.address||"")}</p></div></article>`).join("")||"<p>Nenhum cliente registrado.</p>"}
const settingsForm=document.querySelector("[data-settings-form]");async function loadSettings(){const{data,error}=await supabase.from("store_settings").select("*").eq("id",true).single();if(error)return say(error.message);Object.keys(data).forEach(k=>{if(settingsForm.elements[k])settingsForm.elements[k].value=data[k]??""})}settingsForm.addEventListener("submit",async e=>{e.preventDefault();const v=new FormData(settingsForm),payload={store_name:v.get("store_name"),whatsapp_number:v.get("whatsapp_number"),instagram_url:v.get("instagram_url")||null,contact_email:v.get("contact_email")||null,address:v.get("address")||null,default_shipping:Number(v.get("default_shipping")||0)};const{error}=await supabase.from("store_settings").update(payload).eq("id",true);say(error?error.message:"Informações da loja salvas.")});
const musicForm=document.querySelector("[data-music-form]"),musicCoverPreview=document.querySelector("[data-music-cover-preview]"),musicOpacityOutput=document.querySelector("[data-music-opacity-output]");
const renderMusicCover=(url)=>{musicCoverPreview.innerHTML=url?`<img src="${escapeHtml(url)}" alt="Capa atual da playlist">`:"<span>AM</span>"};
async function loadMusicSettings(){const{data,error}=await supabase.from("store_settings").select("music_enabled,music_spotify_url,music_title,music_description,music_cover_url,music_bar_text,music_button_text,music_position,music_scope,music_background_color,music_opacity,music_show_cover,music_initial_state").eq("id",true).single();if(error)return say(error.message);Object.entries(data).forEach(([key,value])=>{const field=musicForm.elements[key];if(!field)return;if(field.type==="checkbox")field.checked=Boolean(value);else field.value=value??""});musicForm.dataset.coverUrl=data.music_cover_url||"";renderMusicCover(data.music_cover_url);musicOpacityOutput.textContent=`${Math.round(Number(data.music_opacity)*100)}%`}
musicForm.elements.music_opacity.addEventListener("input",()=>{musicOpacityOutput.textContent=`${Math.round(Number(musicForm.elements.music_opacity.value)*100)}%`});
musicForm.elements.music_cover_file.addEventListener("change",()=>{const file=musicForm.elements.music_cover_file.files[0];if(!file)return;const preview=URL.createObjectURL(file);renderMusicCover(preview);musicCoverPreview.querySelector("img")?.addEventListener("load",()=>URL.revokeObjectURL(preview),{once:true})});
const normalizeSpotifyPlaylistUrl=(value)=>{try{const url=new URL(value);if(url.hostname!=="open.spotify.com")return null;const parts=url.pathname.split("/").filter(Boolean),offset=parts[0]?.startsWith("intl-")?1:0,embedOffset=parts[offset]==="embed"?offset+1:offset;if(parts[embedOffset]!=="playlist"||!parts[embedOffset+1])return null;return`https://open.spotify.com/embed/playlist/${encodeURIComponent(parts[embedOffset+1])}?utm_source=generator`}catch{return null}};
musicForm.elements.music_spotify_url.addEventListener("input",()=>musicForm.elements.music_spotify_url.setCustomValidity(""));
musicForm.addEventListener("submit",e=>{const field=musicForm.elements.music_spotify_url,raw=field.value.trim();if(!raw)return;const normalized=normalizeSpotifyPlaylistUrl(raw);if(normalized){field.value=normalized;return}e.preventDefault();e.stopImmediatePropagation();field.setCustomValidity("Informe um link válido de playlist do Spotify.");field.reportValidity()},{capture:true});
musicForm.addEventListener("submit",async e=>{e.preventDefault();const button=musicForm.querySelector('button[type="submit"]');button.disabled=true;say("Salvando Música da Casa…");const v=new FormData(musicForm);let coverUrl=musicForm.dataset.coverUrl||null;const coverFile=musicForm.elements.music_cover_file.files[0];if(coverFile){if(!["image/jpeg","image/png","image/webp"].includes(coverFile.type)){button.disabled=false;return say("Use uma capa em JPG, PNG ou WebP.")}const safe=coverFile.name.normalize("NFD").replace(/[^a-zA-Z0-9._-]/g,"-").toLowerCase();const path=`music/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("store-assets").upload(path,coverFile,{contentType:coverFile.type,upsert:false});if(uploadError){button.disabled=false;return say(`Não foi possível enviar a capa: ${uploadError.message}`)}const{data:url}=supabase.storage.from("store-assets").getPublicUrl(path);coverUrl=url.publicUrl}const payload={music_enabled:v.get("music_enabled")==="on",music_spotify_url:v.get("music_spotify_url")||null,music_title:v.get("music_title").trim(),music_description:v.get("music_description").trim(),music_cover_url:coverUrl,music_bar_text:v.get("music_bar_text").trim(),music_button_text:v.get("music_button_text").trim(),music_position:v.get("music_position"),music_scope:v.get("music_scope"),music_background_color:v.get("music_background_color"),music_opacity:Number(v.get("music_opacity")),music_show_cover:v.get("music_show_cover")==="on",music_initial_state:v.get("music_initial_state")};const{error}=await supabase.from("store_settings").update(payload).eq("id",true);button.disabled=false;if(error)return say(error.message);musicForm.dataset.coverUrl=coverUrl||"";musicForm.elements.music_cover_file.value="";renderMusicCover(coverUrl);localStorage.removeItem("amoremio:house-music-state");localStorage.setItem("amoremio:house-music-config-change",JSON.stringify({at:Date.now(),enabled:payload.music_enabled,playlist:payload.music_spotify_url}));say("Configurações da Música da Casa salvas.")});
if(session)initDataBackups({supabase,user:session.user,say});
await Promise.all([loadCategories(),loadProducts(),loadSettings(),loadMusicSettings()]);
